# Generated by Django 3.1.6 on 2021-02-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'), ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'), ('Employment', 'Employment')], max_length=15, verbose_name='First Topic')),
                ('topic2', models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'), ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'), ('Employment', 'Employment')], max_length=15, verbose_name='Second Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HEALSurvey.question')),
            ],
        ),
    ]
