# Generated by Django 3.1.6 on 2021-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'), ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'), ('Employment', 'Employment')], max_length=15)),
                ('topic2', models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'), ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'), ('Employment', 'Employment')], max_length=15)),
            ],
        ),
    ]
