# Generated by Django 3.1.6 on 2021-03-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0003_auto_20210302_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ImageLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='VideoLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='WebsiteLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
