# Generated by Django 3.1.6 on 2021-03-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0004_auto_20210303_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ImageLink',
            new_name='WebsiteLinkAlt',
        ),
        migrations.AddField(
            model_name='question',
            name='InfoText',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Strongly disagree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree'), ('Not at all', 'Not at all'), ('Somewhat', 'Somewhat'), ('Familiar', 'Familiar'), ('Very familiar', 'Very familiar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionText',
            field=models.CharField(max_length=600),
        ),
    ]
