# Generated by Django 3.1.6 on 2021-03-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0005_auto_20210310_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='VideoLink',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='WebsiteLink',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='WebsiteLinkAlt',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic',
            field=models.CharField(blank=True,
                                   choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'),
                                            ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'),
                                            ('Employment', 'Employment')], max_length=15, null=True,
                                   verbose_name='First Topic'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic2',
            field=models.CharField(blank=True,
                                   choices=[('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'),
                                            ('Healthy Food', 'Healthy Food'), ('Housing', 'Housing'),
                                            ('Employment', 'Employment')], max_length=15, null=True,
                                   verbose_name='Second Topic'),
        ),
    ]
