# Generated by Django 3.1.6 on 2021-04-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0006_auto_20210316_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('True', 'True'), ('False', 'False'), ('Strongly disagree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree'), ('Not at all', 'Not at all'), ('Somewhat', 'Somewhat'), ('Familiar', 'Familiar'), ('Very familiar', 'Very familiar')], max_length=20),
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HEALSurvey.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medianFamilyIncome', models.CharField(max_length=30)),
                ('twoBedroomHousingWage', models.CharField(max_length=30)),
                ('prevalenceDiabetesInAdults', models.CharField(max_length=30)),
                ('walkScore', models.CharField(max_length=30)),
                ('housingTransportationAffordability', models.CharField(max_length=30)),
                ('healthyFoodAccess', models.CharField(max_length=30)),
                ('asthmaRate', models.CharField(max_length=30)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HEALSurvey.city')),
                ('zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HEALSurvey.zipcode')),
            ],
        ),
    ]
