# Generated by Django 3.1.6 on 2021-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0007_auto_20210331_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('u_choice', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SummaryChoice',
        ),
    ]
