# Generated by Django 3.1.6 on 2021-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0009_auto_20210331_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('True', 'True'), ('False', 'False'), ('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree'), ('Not at all', 'Not at all'), ('Somewhat', 'Somewhat'), ('Familiar', 'Familiar'), ('Very familiar', 'Very familiar')], max_length=20),
        ),
    ]
