# Generated by Django 3.1.6 on 2021-04-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HEALSurvey', '0014_zipcodedata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zipcodedata',
            table='HEALSurvey_zipcodedata',
        ),
    ]
