# Generated by Django 3.1.6 on 2021-04-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HEALSurvey', '0015_auto_20210416_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='u_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
